/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */

export namespace RNCCameraRollPermission {
  export const NAME = 'RNCCameraRollPermission' as const

  export interface Spec {
    checkPermission(content: string): Promise<string>;
  
    requestReadWritePermission(): Promise<string>;
  
    requestAddOnlyPermission(): Promise<string>;
  
    refreshPhotoSelection(): Promise<boolean>;
  
    addListener(eventName: string): void;
  
    removeListeners(count: number): void;
  
  }
}
